server:
  port: 9001

spring:
  application:
    name: gateway-demo
  boot:
    admin:
      client:
        url: http://localhost:8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    
zuul:
  routes:
    pfs-ifind-web.path: /psf/** #路由转发
    pfs-ifind-web.serviceId: web-demo

logging:
  level:
    com.myhexin: debug
    root: warn
