server:
  port: 8081

spring:
  application:
    name: service-demo
  boot:
    admin:
      client:
        url: http://localhost:8788
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url


logging:
  level:
    com.myhexin: debug
    root: warn
